<?php

namespace Database\Seeders;

use App\Models\Dispositivo;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DispositivoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Dispositivo::create(['codigo' => '150230-12', 'fecha' => '2022-04-03', 'nombre' => 'pantalla led ', 'tamano' => '24 plg', 'marca' => 'lg', 'modelo' => 'xxs-300', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150231-12', 'fecha' => '2022-04-03', 'nombre' => 'teclado de menbrana', 'tamano' => '104 teclas', 'marca' => 'dell', 'modelo' => 'te-213', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150232-12', 'fecha' => '2022-04-03', 'nombre' => 'mouse mecanico', 'tamano' => '5plg', 'marca' => 'delux', 'modelo' => 'n322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150233-12', 'fecha' => '2022-04-03', 'nombre' => 'parlantes deluz', 'tamano' => '152 x 228 x 225 mm', 'marca' => 'delux', 'modelo' => 'n23', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150234-12', 'fecha' => '2022-04-03', 'nombre' => 'impresora', 'tamano' => '1189 x 594 mm', 'marca' => 'hp', 'modelo' => 'g32', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150235-12', 'fecha' => '2022-04-03', 'nombre' => 'Escanner', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'esc322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150236-12', 'fecha' => '2022-04-03', 'nombre' => 'Dta show ', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'dt-34', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150237-12', 'fecha' => '2022-04-03', 'nombre' => 'pantalla lcd', 'tamano' => '24 plg', 'marca' => 'lg', 'modelo' => 'xxs-300', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150238-12', 'fecha' => '2022-04-03', 'nombre' => 'teclado de mecanico', 'tamano' => '104 teclas', 'marca' => 'dell', 'modelo' => 'te-213', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150239-12', 'fecha' => '2022-04-03', 'nombre' => 'mouse optico', 'tamano' => '5plg', 'marca' => 'delux', 'modelo' => 'n322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150240-12', 'fecha' => '2022-04-03', 'nombre' => 'parlantes deluz', 'tamano' => '152 x 228 x 225 mm', 'marca' => 'delux', 'modelo' => 'n23', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150241-12', 'fecha' => '2022-04-03', 'nombre' => 'impresora', 'tamano' => '1189 x 594 mm', 'marca' => 'hp', 'modelo' => 'g32', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150230-13', 'fecha' => '2022-04-03', 'nombre' => 'Escanner', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'esc322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150231-13', 'fecha' => '2022-04-03', 'nombre' => 'Dta show ', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'dt-34', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150232-13', 'fecha' => '2022-04-03', 'nombre' => 'pantalla amoled', 'tamano' => '24 plg', 'marca' => 'lg', 'modelo' => 'xxs-300', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150233-13', 'fecha' => '2022-04-03', 'nombre' => 'teclado de mecanico', 'tamano' => '104 teclas', 'marca' => 'dell', 'modelo' => 'te-213', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150234-13', 'fecha' => '2022-04-03', 'nombre' => 'mouse a bluehod', 'tamano' => '5plg', 'marca' => 'delux', 'modelo' => 'n322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150235-13', 'fecha' => '2022-04-03', 'nombre' => 'parlantes deluz', 'tamano' => '152 x 228 x 225 mm', 'marca' => 'delux', 'modelo' => 'n23', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150236-13', 'fecha' => '2022-04-03', 'nombre' => 'impresora', 'tamano' => '1189 x 594 mm', 'marca' => 'hp', 'modelo' => 'g32', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150237-13', 'fecha' => '2022-04-03', 'nombre' => 'Escanner', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'esc322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150238-13', 'fecha' => '2022-04-03', 'nombre' => 'Dta show ', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'dt-34', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150239-13', 'fecha' => '2022-04-03', 'nombre' => 'pantalla lcd', 'tamano' => '32 plg', 'marca' => 'lg', 'modelo' => 'xxs-300', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150240-13', 'fecha' => '2022-04-03', 'nombre' => 'teclado de mecanico', 'tamano' => '104 teclas', 'marca' => 'dell', 'modelo' => 'te-213', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150241-13', 'fecha' => '2022-04-03', 'nombre' => 'mouse a bluehod', 'tamano' => '5plg', 'marca' => 'delux', 'modelo' => 'n322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150230-14', 'fecha' => '2022-04-03', 'nombre' => 'parlantes deluz', 'tamano' => '152 x 228 x 225 mm', 'marca' => 'delux', 'modelo' => 'n23', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150231-14', 'fecha' => '2022-04-03', 'nombre' => 'impresora', 'tamano' => '1189 x 594 mm', 'marca' => 'hp', 'modelo' => 'g32', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150232-14', 'fecha' => '2022-04-03', 'nombre' => 'Escanner', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'esc322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150233-14', 'fecha' => '2022-04-03', 'nombre' => 'Dta show ', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'dt-34', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150234-14', 'fecha' => '2022-04-03', 'nombre' => 'pantalla lcd', 'tamano' => '32 plg', 'marca' => 'lg', 'modelo' => 'xxs-300', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150235-14', 'fecha' => '2022-06-02', 'nombre' => 'pantalla lcd', 'tamano' => '32 plg', 'marca' => 'lg', 'modelo' => 'xxs-300', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150236-14', 'fecha' => '2022-06-02', 'nombre' => 'teclado de mecanico', 'tamano' => '104 teclas', 'marca' => 'dell', 'modelo' => 'te-213', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150237-14', 'fecha' => '2022-06-02', 'nombre' => 'mouse a bluehod', 'tamano' => '5plg', 'marca' => 'delux', 'modelo' => 'n322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150238-14', 'fecha' => '2022-06-02', 'nombre' => 'parlantes deluz', 'tamano' => '152 x 228 x 225 mm', 'marca' => 'delux', 'modelo' => 'n23', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150239-14', 'fecha' => '2022-06-02', 'nombre' => 'impresora', 'tamano' => '1189 x 594 mm', 'marca' => 'hp', 'modelo' => 'g32', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150240-14', 'fecha' => '2022-06-02', 'nombre' => 'Escanner', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'esc322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150230-15', 'fecha' => '2022-06-02', 'nombre' => 'Dta show ', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'dt-34', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150231-15', 'fecha' => '2022-06-02', 'nombre' => 'pantalla led ', 'tamano' => '24 plg', 'marca' => 'lg', 'modelo' => 'xxs-300', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150232-15', 'fecha' => '2022-06-02', 'nombre' => 'teclado de menbrana', 'tamano' => '104 teclas', 'marca' => 'dell', 'modelo' => 'te-213', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150233-15', 'fecha' => '2022-06-02', 'nombre' => 'mouse mecanico', 'tamano' => '5plg', 'marca' => 'delux', 'modelo' => 'n322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150234-15', 'fecha' => '2022-06-02', 'nombre' => 'parlantes deluz', 'tamano' => '152 x 228 x 225 mm', 'marca' => 'delux', 'modelo' => 'n23', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150235-15', 'fecha' => '2022-06-02', 'nombre' => 'impresora', 'tamano' => '1189 x 594 mm', 'marca' => 'hp', 'modelo' => 'g32', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150236-15', 'fecha' => '2022-06-02', 'nombre' => 'Escanner', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'esc322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150237-15', 'fecha' => '2022-06-20', 'nombre' => 'Dta show ', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'dt-34', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150238-15', 'fecha' => '2022-06-20', 'nombre' => 'pantalla lcd', 'tamano' => '24 plg', 'marca' => 'lg', 'modelo' => 'xxs-300', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150239-15', 'fecha' => '2022-06-20', 'nombre' => 'teclado de mecanico', 'tamano' => '104 teclas', 'marca' => 'dell', 'modelo' => 'te-213', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150230-16', 'fecha' => '2022-06-20', 'nombre' => 'mouse optico', 'tamano' => '5plg', 'marca' => 'delux', 'modelo' => 'n322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150231-16', 'fecha' => '2022-06-20', 'nombre' => 'parlantes deluz', 'tamano' => '152 x 228 x 225 mm', 'marca' => 'delux', 'modelo' => 'n23', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150232-16', 'fecha' => '2022-06-20', 'nombre' => 'impresora', 'tamano' => '1189 x 594 mm', 'marca' => 'hp', 'modelo' => 'g32', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150233-16', 'fecha' => '2022-06-20', 'nombre' => 'Escanner', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'esc322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150234-16', 'fecha' => '2022-06-20', 'nombre' => 'Dta show ', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'dt-34', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150235-16', 'fecha' => '2022-06-20', 'nombre' => 'pantalla amoled', 'tamano' => '24 plg', 'marca' => 'lg', 'modelo' => 'xxs-300', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150236-16', 'fecha' => '2022-06-20', 'nombre' => 'teclado de mecanico', 'tamano' => '104 teclas', 'marca' => 'dell', 'modelo' => 'te-213', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150237-16', 'fecha' => '2022-06-20', 'nombre' => 'mouse a bluehod', 'tamano' => '5plg', 'marca' => 'delux', 'modelo' => 'n322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150238-16', 'fecha' => '2022-06-20', 'nombre' => 'parlantes deluz', 'tamano' => '152 x 228 x 225 mm', 'marca' => 'delux', 'modelo' => 'n23', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150239-16', 'fecha' => '2022-06-20', 'nombre' => 'impresora', 'tamano' => '1189 x 594 mm', 'marca' => 'hp', 'modelo' => 'g32', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150240-16', 'fecha' => '2022-06-20', 'nombre' => 'Escanner', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'esc322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150241-16', 'fecha' => '2022-06-20', 'nombre' => 'Dta show ', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'dt-34', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150230-17', 'fecha' => '2022-06-20', 'nombre' => 'pantalla led ', 'tamano' => '24 plg', 'marca' => 'lg', 'modelo' => 'xxs-300', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150231-17', 'fecha' => '2022-06-20', 'nombre' => 'teclado de menbrana', 'tamano' => '104 teclas', 'marca' => 'dell', 'modelo' => 'te-213', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150232-17', 'fecha' => '2022-06-20', 'nombre' => 'mouse mecanico', 'tamano' => '5plg', 'marca' => 'delux', 'modelo' => 'n322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150233-17', 'fecha' => '2022-06-20', 'nombre' => 'parlantes deluz', 'tamano' => '152 x 228 x 225 mm', 'marca' => 'delux', 'modelo' => 'n23', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150234-17', 'fecha' => '2022-06-20', 'nombre' => 'impresora', 'tamano' => '1189 x 594 mm', 'marca' => 'hp', 'modelo' => 'g32', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150235-17', 'fecha' => '2022-06-20', 'nombre' => 'Escanner', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'esc322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150236-17', 'fecha' => '2022-07-10', 'nombre' => 'Dta show ', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'dt-34', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150237-17', 'fecha' => '2022-07-10', 'nombre' => 'pantalla lcd', 'tamano' => '24 plg', 'marca' => 'lg', 'modelo' => 'xxs-300', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150238-17', 'fecha' => '2022-07-10', 'nombre' => 'teclado de mecanico', 'tamano' => '104 teclas', 'marca' => 'dell', 'modelo' => 'te-213', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150239-17', 'fecha' => '2022-07-10', 'nombre' => 'mouse optico', 'tamano' => '5plg', 'marca' => 'delux', 'modelo' => 'n322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150240-17', 'fecha' => '2022-07-10', 'nombre' => 'parlantes deluz', 'tamano' => '152 x 228 x 225 mm', 'marca' => 'delux', 'modelo' => 'n23', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150241-17', 'fecha' => '2022-07-10', 'nombre' => 'impresora', 'tamano' => '1189 x 594 mm', 'marca' => 'hp', 'modelo' => 'g32', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150230-18', 'fecha' => '2022-07-10', 'nombre' => 'Escanner', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'esc322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150231-18', 'fecha' => '2022-07-10', 'nombre' => 'Dta show ', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'dt-34', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150232-18', 'fecha' => '2022-07-10', 'nombre' => 'pantalla amoled', 'tamano' => '24 plg', 'marca' => 'lg', 'modelo' => 'xxs-300', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150233-18', 'fecha' => '2022-07-10', 'nombre' => 'teclado de mecanico', 'tamano' => '104 teclas', 'marca' => 'dell', 'modelo' => 'te-213', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150234-18', 'fecha' => '2022-07-10', 'nombre' => 'mouse a bluehod', 'tamano' => '5plg', 'marca' => 'delux', 'modelo' => 'n322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150235-18', 'fecha' => '2022-07-10', 'nombre' => 'parlantes deluz', 'tamano' => '152 x 228 x 225 mm', 'marca' => 'delux', 'modelo' => 'n23', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150236-18', 'fecha' => '2022-07-10', 'nombre' => 'impresora', 'tamano' => '1189 x 594 mm', 'marca' => 'hp', 'modelo' => 'g32', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150237-18', 'fecha' => '2022-07-10', 'nombre' => 'Escanner', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'esc322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150238-18', 'fecha' => '2022-07-10', 'nombre' => 'Dta show ', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'dt-34', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150239-18', 'fecha' => '2022-07-10', 'nombre' => 'pantalla led ', 'tamano' => '24 plg', 'marca' => 'lg', 'modelo' => 'xxs-300', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150240-18', 'fecha' => '2022-07-10', 'nombre' => 'teclado de menbrana', 'tamano' => '104 teclas', 'marca' => 'dell', 'modelo' => 'te-213', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150230-18', 'fecha' => '2022-07-10', 'nombre' => 'mouse mecanico', 'tamano' => '5plg', 'marca' => 'delux', 'modelo' => 'n322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150231-18', 'fecha' => '2022-07-10', 'nombre' => 'parlantes deluz', 'tamano' => '152 x 228 x 225 mm', 'marca' => 'delux', 'modelo' => 'n23', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150232-18', 'fecha' => '2022-07-10', 'nombre' => 'impresora', 'tamano' => '1189 x 594 mm', 'marca' => 'hp', 'modelo' => 'g32', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150233-18', 'fecha' => '2022-07-10', 'nombre' => 'Escanner', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'esc322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150234-18', 'fecha' => '2022-07-10', 'nombre' => 'Dta show ', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'dt-34', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150235-18', 'fecha' => '2022-07-10', 'nombre' => 'pantalla lcd', 'tamano' => '24 plg', 'marca' => 'lg', 'modelo' => 'xxs-300', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150236-18', 'fecha' => '2022-07-10', 'nombre' => 'teclado de mecanico', 'tamano' => '104 teclas', 'marca' => 'dell', 'modelo' => 'te-213', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150237-18', 'fecha' => '2022-07-10', 'nombre' => 'mouse optico', 'tamano' => '5plg', 'marca' => 'delux', 'modelo' => 'n322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150238-18', 'fecha' => '2022-07-10', 'nombre' => 'parlantes deluz', 'tamano' => '152 x 228 x 225 mm', 'marca' => 'delux', 'modelo' => 'n23', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150239-19', 'fecha' => '2022-07-10', 'nombre' => 'impresora', 'tamano' => '1189 x 594 mm', 'marca' => 'hp', 'modelo' => 'g32', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150230-19', 'fecha' => '2022-09-12', 'nombre' => 'Escanner', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'esc322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150231-19', 'fecha' => '2022-09-12', 'nombre' => 'Dta show ', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'dt-34', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150232-19', 'fecha' => '2022-09-12', 'nombre' => 'pantalla amoled', 'tamano' => '24 plg', 'marca' => 'lg', 'modelo' => 'xxs-300', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150233-19', 'fecha' => '2022-09-12', 'nombre' => 'teclado de mecanico', 'tamano' => '104 teclas', 'marca' => 'dell', 'modelo' => 'te-213', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150234-19', 'fecha' => '2022-09-12', 'nombre' => 'mouse a bluehod', 'tamano' => '5plg', 'marca' => 'delux', 'modelo' => 'n322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150235-19', 'fecha' => '2022-09-12', 'nombre' => 'parlantes deluz', 'tamano' => '152 x 228 x 225 mm', 'marca' => 'delux', 'modelo' => 'n23', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150236-19', 'fecha' => '2022-09-12', 'nombre' => 'impresora', 'tamano' => '1189 x 594 mm', 'marca' => 'hp', 'modelo' => 'g32', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150237-19', 'fecha' => '2022-09-12', 'nombre' => 'Escanner', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'esc322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150238-19', 'fecha' => '2022-09-12', 'nombre' => 'Dta show ', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'dt-34', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150239-19', 'fecha' => '2022-09-12', 'nombre' => 'pantalla led ', 'tamano' => '24 plg', 'marca' => 'lg', 'modelo' => 'xxs-300', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150240-19', 'fecha' => '2022-09-12', 'nombre' => 'teclado de menbrana', 'tamano' => '104 teclas', 'marca' => 'dell', 'modelo' => 'te-213', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150241-19', 'fecha' => '2022-09-12', 'nombre' => 'mouse mecanico', 'tamano' => '5plg', 'marca' => 'delux', 'modelo' => 'n322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150230-20', 'fecha' => '2022-09-12', 'nombre' => 'parlantes deluz', 'tamano' => '152 x 228 x 225 mm', 'marca' => 'delux', 'modelo' => 'n23', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150231-20', 'fecha' => '2022-09-12', 'nombre' => 'impresora', 'tamano' => '1189 x 594 mm', 'marca' => 'hp', 'modelo' => 'g32', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150232-20', 'fecha' => '2022-09-12', 'nombre' => 'Escanner', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'esc322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150233-20', 'fecha' => '2022-09-12', 'nombre' => 'Dta show ', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'dt-34', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150234-20', 'fecha' => '2022-09-12', 'nombre' => 'pantalla lcd', 'tamano' => '24 plg', 'marca' => 'lg', 'modelo' => 'xxs-300', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150235-20', 'fecha' => '2022-09-12', 'nombre' => 'teclado de mecanico', 'tamano' => '104 teclas', 'marca' => 'dell', 'modelo' => 'te-213', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150236-120', 'fecha' => '2022-09-12', 'nombre' => 'mouse optico', 'tamano' => '5plg', 'marca' => 'delux', 'modelo' => 'n322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150237-20', 'fecha' => '2022-09-12', 'nombre' => 'parlantes deluz', 'tamano' => '152 x 228 x 225 mm', 'marca' => 'delux', 'modelo' => 'n23', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150238-120', 'fecha' => '2022-09-12', 'nombre' => 'impresora', 'tamano' => '1189 x 594 mm', 'marca' => 'hp', 'modelo' => 'g32', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150239-20', 'fecha' => '2022-09-12', 'nombre' => 'Escanner', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'esc322', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150240-20', 'fecha' => '2022-09-12', 'nombre' => 'Dta show ', 'tamano' => '216 x 356 mm', 'marca' => 'hp', 'modelo' => 'dt-34', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150241-20', 'fecha' => '2022-09-12', 'nombre' => 'pantalla led ', 'tamano' => '24 plg', 'marca' => 'lg', 'modelo' => 'xxs-300', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 1, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150230-21', 'fecha' => '2022-09-12', 'nombre' => 'pantalla led ', 'tamano' => '24 plg', 'marca' => 'lg', 'modelo' => 'xxs-300', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
        Dispositivo::create(['codigo' => '150231-21', 'fecha' => '2022-09-12', 'nombre' => 'pantalla led ', 'tamano' => '24 plg', 'marca' => 'lg', 'modelo' => 'xxs-300', 'descripcion' => 'sin decripcion', 'estado' => '1', 'tecnico_id' => 2, 'entrega' => 0, 'reparacion' => 0, 'prestamo' => 0, 'devolucion' => 0, 'almacen' => 0, 'repliegue' => 0,]);
    }
}
